- id: boiler_shower
  alias: Alert shower time
  trigger:
    platform: mqtt
    topic: home/boiler/showertime
  action:
    - service: notify.general_notify
      data_template:
        title: "Shower finished at {{states.sensor.time.state}}"
        message: '{{trigger.payload}}'

- id: boiler_shower_alarm
  alias: Alert shower too long
  trigger:
    platform: mqtt
    topic: home/boiler/command
    payload: 'shower_alarm'
  action:
    - service: notify.admin_notify
      data_template:
        title: "Shower Alert!"
        message: "Shower time exceeded limit"

# when boiler starts send boottime
- id: boiler_restart
  alias: See if boiler restarts
  trigger:
    platform: mqtt
    topic: home/boiler/start
    payload: 'start'
  action:
    - service: notify.admin_notify
      data_template:
        title: "boiler has booted"
        message: "Boiler"
    - service: mqtt.publish
      data_template:
        topic: 'home/boiler/start'
        payload: >
          {{ now().strftime("%H:%M:%S %-d/%b/%Y") }}



