title: Home
views:
  
  - title: Heating
    cards:
      - type: entities
        title: Boiler
        show_header_toggle: false
        entities:
          - sensor.boiler_boottime
          - sensor.boiler_updated
          - type: divider
          - sensor.warm_water_selected_temperature
          - sensor.warm_water_current_temperature
          - sensor.warm_water_activated
          - sensor.warm_water_3_way_valve
          - sensor.warm_water_tapwater_flow_rate
          - type: divider
          - sensor.boiler_temperature
          - sensor.return_temperature
          - sensor.current_flow_temperature
          - sensor.pump_modulation
          - sensor.ignition
          - sensor.gas
          - sensor.fan
          - sensor.boiler_pump
          - sensor.system_pressure
          - sensor.burner_max_power
          - sensor.burner_current_power
          
      - type: vertical-stack
        cards:
        - type: entities
          title: Shower Monitor
          show_header_toggle: false
          entities:
            - switch.shower_timer
            - switch.long_shower_alert
            - type: divider
            - sensor.last_shower_duration
            - sensor.showertime_time
        - type: custom:button-card
          color: auto
          icon: mdi:shower-head
          name: send a cold shot of shower water
          style:
            - text-transform: none
            - color: rgb(28, 128, 199)
            - font-weight: bold
          entity: script.shower_coldshot
          show_state: false
            
      - type: vertical-stack
        cards:       
        - type: history-graph
          entities:
            - sensor.current_room_temperature
            - sensor.dark_sky_temperature
        - type: thermostat
          entity: climate.thermostat
