resources:
  - url: /local/custom-lovelace/thermostat-card/thermostat-card.js
    type: module

title: Home
views:
  
  - title: Heating
    cards:
      - type: entities
        title: Boiler
        show_header_toggle: true
        entities:
          - sensor.boiler_boottime
          - sensor.boiler_updated
          - type: divider
          - input_number.boiler_wwtemp
          - sensor.warm_water_current_temperature
          - sensor.warm_water_activated
          - sensor.warm_water_3way_valve
          - type: divider
          - sensor.boiler_temperature
          - sensor.return_temperature
          - sensor.current_flow_temperature
          - sensor.pump_modulation
          - sensor.ignition
          - sensor.gas
          - sensor.fan
          - sensor.boiler_pump
          - sensor.system_pressure
          - sensor.burner_max_power
          - sensor.burner_current_power
          
      - type: vertical-stack
        cards:
        - type: entities
          title: Shower Monitor
          show_header_toggle: true
          entities:
            - switch.shower_timer
            - switch.long_shower_alert
            - type: divider
            - sensor.last_shower_duration
            - sensor.showertime_time
        - type: custom:button-card
          color: auto
          icon: mdi:shower-head
          name: send a cold shot of shower water
          style:
            - text-transform: none
            - color: rgb(28, 128, 199)
            - font-weight: bold
          entity: script.shower_coldshot
          show_state: false
            
      - type: vertical-stack
        cards:       
        - type: entities
          title: Thermostat
          show_header_toggle: true
          entities:
            - sensor.current_room_temperature
            - sensor.current_mode
            - input_number.thermostat_temp
        - type: history-graph
          entities:
            - sensor.current_room_temperature
            - sensor.dark_sky_temperature
        - type: custom:thermostat-card
          title: Living Room
          entity: climate.thermostat
          pending: 1
          chevron_size: 50
          no_card: false
          hvac:
            states:
              'low': 'low'
              'manual': 'manual'
              'auto': 'auto'
            attribute: operation_mode
          highlight_tap: true
  